[[CURRENCIES]]
code="AIRLIE"
issuer="GDOW56GS47XLRDMJ4KPPAMRU6IZ57BIG5M26XMXIKFC7VY7D6TYBWSDR"
image="https://ntkleme.github.io/airlie-token-assets/Copilot_20251110_122809.2.jpg"
desc="Community-driven conservation token"
