[[CURRENCIES]]
code="AIRLIE"
issuer="GDOW56GS47XLRDMJ4KPPAMRU6IZ57BIG5M26XMXIKFC7VY7D6TYBWSDR"
image="https://yourusername.github.io/airlie-token-assets/airlie.jpg"
desc="Community-driven conservation token"
